name: Pages
on: workflow_dispatch
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - uses: actions/deploy-pages@v4
